general.import = [
"~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
opacity = 0.85
decorations = "Full"
decorations_theme_variant = "Dark"

[window.padding]
x = 12
y = 12

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"

# === GRUVBOX ===
# [colors.primary]
# background = "#282828"
# foreground = "#fbf7c1"
#
# [colors.cursor]
# text = "#fbf7c1"
# cursor = "#fbf7c1"
# === ======= ===

[scrolling]
history = 10000
multiplier = 3

[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
]

[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/usr/bin/tmux"
args = ["new-session", "-A", "-D", "-s", "home"]
